# Generated by Django 4.2.2 on 2023-06-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_profile_delete_useradmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='profile_set', to='auth.group'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='profile_set', to='auth.permission'),
        ),
    ]
