# Generated by Django 4.2.2 on 2023-07-05 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_contactformentry'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contactformentry',
            table='contact_form',
        ),
    ]
